### ISSUE TITLE
keras error when using new dcase_util 0.2.13

### ISSUE THREAD

**Issue by arunodhayan** [DCASE-REPO/dcase_util#31]
File "/src/task1a.py", line 683, in do_learning
    print_indent=2
  File "/usr/local/lib/python3.6/dist-packages/dcase_util/decorators/decorators.py", line 14, in __call__
    return self.f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dcase_util/keras/utils.py", line 308, in setup_keras
    keras.backend.tensorflow_backend.set_session(tf.Session(config=config))
UnboundLocalError: local variable 'keras' referenced before assignment

**Comment by toni-heittola** [comment]
There is something wrong here, the master branch of this repository is currently in sync with version 0.2.13, however, code line 308 which is producing your error is different in the released version > https://github.com/DCASE-REPO/dcase_util/blob/master/dcase_util/keras/utils.py#L308

Are you sure you are using version 0.2.13 ?

**Comment by arunodhayan** [comment]
[E] Uncaught exception 	(logging.py:221)
Traceback (most recent call last):
  File "task1b.py", line 680, in <module>
    sys.exit(main(sys.argv))
  File "task1b.py", line 234, in main
    overwrite=overwrite
  File "/src/task1a.py", line 683, in do_learning
    print_indent=2
  File "/usr/local/lib/python3.6/dist-packages/dcase_util/decorators/decorators.py", line 14, in __call__
    return self.f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dcase_util/keras/utils.py", line 308, in setup_keras
    keras.backend.tensorflow_backend.set_session(tf.Session(config=config))
UnboundLocalError: local variable 'keras' referenced before assignment

**Comment by toni-heittola** [comment]
Ok, this should be fixed now. You just have to update dcase_util to version 0.2.14 version and it should work. The PIP package for version 0.2.13 was for some reason not in sync with the repository.

**Comment by arunodhayan** [comment]
its working now ty
